tasks:
  # Random utilities 
  - name: cdk
    before: |
          npm i -g aws-cdk
        # cdk bootstrap
        #  cdk synth
        #  cdk deploy
        #  cdk destroy
  - name: terraform
    before: |
          ./bin/terraform_cli_install.sh
  - name: utils 
    before: |
          sudo apt-get install tree
  # https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.4
  # https://docs.aws.amazon.com/powershell/latest/userguide/pstools-getting-set-up-linux-mac.html
  # https://docs.aws.amazon.com/powershell/latest/reference/
  - name: powershell
    before: |
          ./bin/powershell_cli_install.sh
  - name: aws-cli
    env:
          AWS_CLI_AUTO_PROMPT: on-partial
    before: |
          ./bin/aws_cli_install.sh
  - name: sdk-java
    before: |
  # https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/setup-project-maven.html
  # https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html
  - name: sdk-ruby
    before: |
  # https://docs.aws.amazon.com/sdk-for-ruby/v3/api/
  # https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html
  # https://github.com/aws/aws-sdk-ruby
  - name: cfn-cloudformation
    before: |
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html




  # chmod u+x ./bin/*