#!/bin/bash

# VPC IGW SUBNET ASSOC RT 

# check if the argument is not present
if [ -z "$1" ]; then
  echo "Argument is not present."
else
  export VPC_ID="$1"
fi

# check if the argument is not present
if [ -z "$2" ]; then
  echo "Argument is not present."
else
  export IGW_ID="$2"
fi

# check if the argument is not present
if [ -z "$3" ]; then
  echo "Argument is not present."
else
  export SUBNET_ID="$3"
fi

# check if the argument is not present
if [ -z "$4" ]; then
  echo "Argument is not present."
else
  export ASSOC_ID="$4"
fi

# check if the argument is not present
if [ -z "$5" ]; then
  echo "Argument is not present."
else
  export RT_ID="$5"
fi

# detach the IGW

aws ec2 detach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID

# delete IGW

aws ec2 delete-internet-gateway --internet-gateway-id $IGW_ID

# dissociate subnet 

aws ec2 disassociate-route-table --association-id $ASSOC_ID

# delete a subnet 

aws ec2 delete-subnet --subnet-id $SUBNET_ID

# delete a RT (Route Table)

aws ec2 delete-route-table --route-table-id $RT_ID

# delete a VPC

aws ec2 delete-vpc --vpc-id $VPC_ID


