#! /usr/bin/env bash 

# Create our VPC

VPC_ID=$(aws ec2 create-vpc \
--cidr-block "188.19.0.0/16" \
--tag-specifications 'ResourceType=vpc,Tags=[{Key=Name,Value=my-shiny-vpc-darling}]' \
--region us-west-2 \
--query Vpc.VpcId \
--output text)

echo $VPC_ID

# Create an IGW

# Attach an IGW

# Create a new subnet 

# Explicitly associate subnet

# Add a route for our RT (Route Table) to our IGW