#!/usr/bin/env bash

echo "== deploy rds"

STACK_NAME="rds-basic"

# https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/deploy/index.html
aws cloudformation deploy \
--template-file template.yaml \
--capabilities CAPABILITY_NAMED_IAM \
--no-execute-changeset \
--parameter-overrides 
--region us-east-1 \
--stack-name $STACK_NAME

VpcId= WebServerSGGroupId 
RdsSecretArn=arn:aws:secretsmanager:us-east-1:976193260990:secret:MyRdsPassword-AEfa3j
Username= 
Subnets= 