#!/usr/bin/env bash 

echo "== deploy ec2"

STACK_NAME="asg-basic"

aws cloudformation deploy \
--template-file template.yaml \
--capabilities CAPABILITY_NAMED_IAM \
--no-execute-changeset \
--region us-west-1 \
--stack-name $STACK_NAME