#! /usr/bin/env bash 
echo "== delete bucket"

# Check if the first argument is provided
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket shiny-bucket-og"
    exit 1
fi

BUCKET_NAME=$1

# https://docs.aws.amazon.com/cli/latest/reference/s3api/create-bucket.html
aws s3api delete-bucket \
--bucket $BUCKET_NAME 
