version=0.1
[default.package.parameters]
s3_bucket = "my-lambda-artifact-og-7893"
region = "us-east-1"
image_repository = "976193260990.dkr.ecr.us-east-1.amazonaws.com/python-container-example"
[default.deploy.parameters]
s3_bucket = "my-lambda-artifact-og-7893"
region = "us-east-1"
image_repository = "976193260990.dkr.ecr.us-east-1.amazonaws.com/python-container-example"
