#! /usr/bin/env bash 

echo "== deploy s3 bucket via CFN"

STACK_NAME="shiny-stack-og"

aws cloudformation deploy \
--template-file template.yaml \
--no-execute-changeset \
--region us-west-2 \
--stack-name $STACK_NAME