#! /usr/bin/env bash 

# yq -o json policy.yml > policy.json 

aws iam create-policy-version \
    --policy-arn arn:aws:iam::976193260990:policy/my-shiny-og-policy \
    --policy-document "$(yq -o json policy.yml)" \
    --set-as-default

